"""create users, employee_type, and employees table

Revision ID: 3a4c562f593c
Revises: 6840dbe70351
Create Date: 2024-04-07 02:31:35.829032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4c562f593c'
down_revision: Union[str, None] = '6840dbe70351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('employee_type_id', sa.Integer(), nullable=True),
    sa.Column('number_of_leaves', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.String(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_type_id'], ['employee_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('employee_type')
    # ### end Alembic commands ###
